# megabank-gitops/megaweb/base/kustomization.yaml
resources:
  - deployment.yaml

configMapGenerator:
  - name: cluster-config
    literals:
      - cpu_limit=2

vars:
  - name: CPU_LIMIT
    objref:
      kind: ConfigMap
      name: cluster-config
      apiVersion: v1
    fieldref:
      fieldpath: data.cpu_limit

# patchesStrategicMerge:
#   - cpu-limits-patch.yaml