apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: accidhist
    app.kubernetes.io/component: accidhist
    app.kubernetes.io/instance: accidhist
    app.kubernetes.io/name: mbsvc
  name: accidhist
  namespace: megabank-be
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: accidhist
  template:
    metadata:
      labels:
        deployment: accidhist
    spec:
      containers:
      - env:
        - name: ALTSQL_FILE
          valueFrom:
            configMapKeyRef:
              key: ALTSQL_FILE
              name: cm-setenv-mbsvc
        - name: DBHOST
          valueFrom:
            configMapKeyRef:
              key: DBHOST
              name: cm-setenv-mbsvc
        - name: DBNAME
          valueFrom:
            configMapKeyRef:
              key: DBNAME
              name: cm-setenv-mbsvc
        - name: DBPASS
          valueFrom:
            secretKeyRef:
              name: db2pass
              key: DBPASS
        - name: DBPORT
          valueFrom:
            configMapKeyRef:
              key: DBPORT
              name: cm-setenv-mbsvc
        - name: DBSCHEMA
          valueFrom:
            configMapKeyRef:
              key: DBSCHEMA
              name: cm-setenv-mbsvc
        - name: DBUSER
          valueFrom:
            configMapKeyRef:
              key: DBUSER
              name: cm-setenv-mbsvc
        - name: INSERT_INTO_HISTORY
          valueFrom:
            configMapKeyRef:
              key: INSERT_INTO_HISTORY
              name: cm-setenv-mbsvc
        - name: JDBCNAME
          valueFrom:
            configMapKeyRef:
              key: JDBCNAME
              name: cm-setenv-mbsvc
        image: quay.io/maduddin/mbsvc:latest
        imagePullPolicy: IfNotPresent
        name: mbsvc-accidhist
        ports:
        - containerPort: 9080
          protocol: TCP
        - containerPort: 9443
          protocol: TCP
        resources: {}
          # limits:
          #   cpu: '250m'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: accidhist
    app.kubernetes.io/component: accidhist
    app.kubernetes.io/instance: accidhist
    app.kubernetes.io/name: mbsvc
  name: accidhist
  namespace: megabank-be
spec:
  ports:
  - name: 9080-tcp
    port: 9080
    protocol: TCP
    targetPort: 9080
  - name: 9443-tcp
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    deployment: accidhist
