apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deposit
    app.kubernetes.io/component: deposit
    app.kubernetes.io/instance: deposit
    app.kubernetes.io/name: mbsvc
  name: deposit
  namespace: megabank-be
spec:
  selector:
    matchLabels:
      deployment: deposit
  template:
    metadata:
      labels:
        deployment: deposit
    spec:
      containers:
      - env:
        - name: ALTSQL_FILE
          valueFrom:
            configMapKeyRef:
              key: ALTSQL_FILE
              name: cm-setenv-mbsvc
        - name: DBHOST
          valueFrom:
            configMapKeyRef:
              key: DBHOST
              name: cm-setenv-mbsvc
        - name: DBNAME
          valueFrom:
            configMapKeyRef:
              key: DBNAME
              name: cm-setenv-mbsvc
        - name: DBPASS
          valueFrom:
            secretKeyRef:
              name: db2pass
              key: DBPASS
        - name: DBPORT
          valueFrom:
            configMapKeyRef:
              key: DBPORT
              name: cm-setenv-mbsvc
        - name: DBSCHEMA
          valueFrom:
            configMapKeyRef:
              key: DBSCHEMA
              name: cm-setenv-mbsvc
        - name: DBUSER
          valueFrom:
            configMapKeyRef:
              key: DBUSER
              name: cm-setenv-mbsvc
        - name: INSERT_INTO_HISTORY
          valueFrom:
            configMapKeyRef:
              key: INSERT_INTO_HISTORY
              name: cm-setenv-mbsvc
        - name: JDBCNAME
          valueFrom:
            configMapKeyRef:
              key: JDBCNAME
              name: cm-setenv-mbsvc
        image: quay.io/mmondics/mmondics/mbsvc:v3-max2500-optimized
        imagePullPolicy: IfNotPresent
        name: mbsvc-deposit
        ports:
        - containerPort: 9080
          protocol: TCP
        - containerPort: 9443
          protocol: TCP
        resources:
          limits:
            cpu: '1500m'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deposit
    app.kubernetes.io/component: deposit
    app.kubernetes.io/instance: deposit
    app.kubernetes.io/name: mbsvc
  name: deposit
  namespace: megabank-be
spec:
  ports:
  - name: 9080-tcp
    port: 9080
    protocol: TCP
    targetPort: 9080
  - name: 9443-tcp
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    deployment: deposit
