apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transfer
    app.kubernetes.io/component: transfer
    app.kubernetes.io/instance: transfer
    app.kubernetes.io/name: mbsvc
  name: transfer
  namespace: megabank-be
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: transfer
  template:
    metadata:
      labels:
        deployment: transfer
    spec:
      containers:
      - env:
        - name: ALTSQL_FILE
          valueFrom:
            configMapKeyRef:
              key: ALTSQL_FILE
              name: cm-setenv-mbsvc
        - name: DBHOST
          valueFrom:
            configMapKeyRef:
              key: DBHOST
              name: cm-setenv-mbsvc
        - name: DBNAME
          valueFrom:
            configMapKeyRef:
              key: DBNAME
              name: cm-setenv-mbsvc
        - name: DBPASS
          valueFrom:
            secretKeyRef:
              name: db2pass
              key: DBPASS
        - name: DBPORT
          valueFrom:
            configMapKeyRef:
              key: DBPORT
              name: cm-setenv-mbsvc
        - name: DBSCHEMA
          valueFrom:
            configMapKeyRef:
              key: DBSCHEMA
              name: cm-setenv-mbsvc
        - name: DBUSER
          valueFrom:
            configMapKeyRef:
              key: DBUSER
              name: cm-setenv-mbsvc
        - name: INSERT_INTO_HISTORY
          valueFrom:
            configMapKeyRef:
              key: INSERT_INTO_HISTORY
              name: cm-setenv-mbsvc
        - name: JDBCNAME
          valueFrom:
            configMapKeyRef:
              key: JDBCNAME
              name: cm-setenv-mbsvc
        - name: LOGGING_LEVEL
          value: debug
        image: quay.io/mmondics/mmondics/mbsvc:20241216165521 
        imagePullPolicy: IfNotPresent
        name: mbsvc-transfer
        ports:
        - containerPort: 9443
          protocol: TCP
        - containerPort: 9080
          protocol: TCP
        resources:
          limits:
            cpu: '2'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: transfer
    app.kubernetes.io/component: transfer
    app.kubernetes.io/instance: transfer
    app.kubernetes.io/name: mbsvc
  name: transfer
  namespace: megabank-be
spec:
  ports:
  - name: 9080-tcp
    port: 9080
    protocol: TCP
    targetPort: 9080
  - name: 9443-tcp
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    deployment: transfer
